#!/bin/bash

if [ ! -f third_party/gyp/gyp ] ; then
  echo "gyp not found, run: "
  echo "  git clone https://chromium.googlesource.com/external/gyp third_party/gyp"
  echo "  cd third_party/gyp"
  echo "  git checkout 27c626e0515f845338cb60b1d8405f40150a791d"
  echo "  cd ../../"
  exit 1
fi

# Generate commit.h
python src/commit_id.py gen src src/commit.h
echo Generated src/commit.h

# Install our generator
cp dump_mozbuild.py third_party/gyp/pylib/gyp/generator

# This will call gyp for each platform
./generate_mozbuild.py
